### ISSUE TITLE
arc.conf management improvement

### ISSUE THREAD

**Issue by martbhell** [CSCfi/ansible-role-arc-frontend#15]
- add handlers to restart arc services if arc.conf (and maybe other things? like certificate) was updated
  - add a tag so one can only update arc.conf with something like:

<pre>
ansible-playbook grid.yml -t arc_conf -D
</pre>

**Comment by A1ve5** [comment]
Better wait to ARC-CE changes promised for this Summer to implement this.

**Comment by A1ve5** [comment]
help wanted here means that we are waiting for external stuff to happen. In this case new ARC release that has major changes in arc.conf syntax and variables.

**Comment by VilleS1** [comment]
Arc services are now always restarted when running playbook.
